#define LOG(x) std::cout<< x << std::endl;

#define PLAYER 1
#define COMPUTER 2

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define MAX_DOTS_LINE 10

#define FPS 60
#define FRAME_TARGET_TIME 1000/FPS

#define BALL_WIDTH 20
#define BALL_HEIGHT 20
#define PLAYER_WIDTH 20
#define PLAYER_HEIGHT 200
#define ENEMY_WIDTH 20
#define ENEMY_HEIGHT 200

#define PAD_MOVEMENT_CONSTANT 450

#define MOVEMENT_HORIZONTAL 0
#define MOVEMENT_VERTICAL 1

#define BALL_MOVEMENT_CONSTANT 250