#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define FPS 60
#define FRAME_TARGET_TIME 1000/FPS

#define BALL_WIDTH 20
#define BALL_HEIGHT 20
#define PLAYER_WIDTH 20
#define PLAYER_HEIGHT 200
#define ENEMY_WIDTH 20
#define ENEMY_HEIGHT 200

#define PAD_MOVEMENT_CONSTANT 350